x-build-context: &build-context
  context: ../
  dockerfile: ./docker/Dockerfile

services:
  npm:
    build:
      <<: *build-context
      target: npm
    user: "${HOST_UID}:${HOST_GID}"
    container_name: app-development-container
    volumes:
      - ../app:/app
    ports:
      - "80:5173"
    tty: true
    stdin_open: true
