services:
  vue-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: my-vue-container
    volumes:
      - ../app:/home/node/app
    ports:
      - "80:5173"
    tty: true
    stdin_open: true
